// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plantId: 1
 *     }
 */
export interface GetByIdPlantRequest {
    /** ID of the plant to retrieve */
    plantId: number;
}
