// This file was auto-generated by Fern from our API Definition.

import type * as AshleyLavizadehApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface SearchByStatusPlantRequest {
    /** The status of plants to search for. */
    status?: AshleyLavizadehApi.SearchByStatusPlantRequestStatus;
}
