// This file was auto-generated by Fern from our API Definition.

export const SearchByStatusPlantRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
export type SearchByStatusPlantRequestStatus =
    (typeof SearchByStatusPlantRequestStatus)[keyof typeof SearchByStatusPlantRequestStatus];
